#! /usr/bin/bash

export LIBDIR=/opt/python/lib/libgpg/lib
# export LIBDIR=/usr/local/lib

export LD_LIBRARY_PATH=${LIBDIR}
export LD_RUN_PATH=${LIBDIR}

source /opt/python/bin/activate

echo ' ==>(1): Clean stale builds.'
rm -rf pygcrypt.c pygcrypt*.so ./build/* 2>/dev/nul

echo ' ==>(2): Determine library evnironment.'
echo 'library: gcrypt could be found and linked via: '
/opt/python/lib/libgpg/bin/libgcrypt-config --libs

echo ' ==>(3): compile cypthon.'
python setup.py build_ext --inplace


echo ' ==>(6): compiling cypthon.'
mv -f ./pygcrypt.cpython-311-x86_64-linux-gnu.so ./pygcrypt.so


chown webdak:users pygcrypt.so pygcrypt.c

ldd ./pygcrypt.so